### ISSUE TITLE
Where to keep my video to run the demo

### ISSUE THREAD

**Issue by arvindchandel** [harsh2912/people-tracking#1]
To run the demo on any video, we need to run:
cd src
python demo.py mot --load_model ../models/all_dla34.pth --conf_thres 0.4

But where should i keep my video, and where to change --input-video and --output-root to get the demos of your own videos.

**Comment by harsh2912** [comment]
You are using demo.py. Please run script.py. Use this code in /src folder :  "**python script.py -mp ../models/all_dla34.pth -vp path_to_video -od path_to_save_video**"

**Comment by arvindchandel** [comment]
While installation following command:
cd src/lib/models/networks/DCNv2_new sh make.sh

Terminates with error:
compilation terminated.
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
